<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <RootNamespace>DeferredEngine</RootNamespace>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks> <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.8.5" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.4.1" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.4.1" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HelperSuite\HelperSuite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <MonoGameContentReference Include="Content\Content.mgcb" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BEPUphysics">
      <HintPath>Content\BEPUphysics.dll</HintPath>
    </Reference>
    <Reference Include="BEPUutilities">
      <HintPath>Content\BEPUutilities.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>